version: "3.8"
services:
  db:
    image: postgres:15.2
    restart: unless-stopped
    container_name: email_app_postgre
    env_file:
      - ./email_app/.env
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  broker:
    image: rabbitmq
    restart: unless-stopped
    container_name: email_app_brocker
    ports:
      - "5672:5672"
  channels:
    image: redis:6.2-alpine
    container_name: email_app_channels
    restart: unless-stopped
    ports:
      - "6379:6379"
    command:
      - /bin/sh
      - -c
      - "redis-server"